// AUTO GENERATED FILE - DO NOT EDIT

const classNames = {
  'attribute': 'attribute',
  'attributes': 'attributes',
  'auth-options': 'auth-options',
  'auth-view': 'auth-view',
  'button': 'button',
  'clickable': 'clickable',
  'content-frame': 'content-frame',
  'content-full-frame': 'content-full-frame',
  'dark': 'dark',
  'error-code': 'error-code',
  'error-container': 'error-container',
  'error-content': 'error-content',
  'error-heading': 'error-heading',
  'error-image': 'error-image',
  'error-message': 'error-message',
  'error-meta': 'error-meta',
  'footer': 'footer',
  'footer-content': 'footer-content',
  'heading-large': 'heading-large',
  'heading-max': 'heading-max',
  'heading-medium': 'heading-medium',
  'heading-small': 'heading-small',
  'home-view': 'home-view',
  'home-view-content': 'home-view-content',
  'home-view-header': 'home-view-header',
  'input': 'input',
  'input-container': 'input-container',
  'large-card': 'large-card',
  'large-card-content': 'large-card-content',
  'large-card-image': 'large-card-image',
  'large-card-image-container': 'large-card-image-container',
  'large-card-link': 'large-card-link',
  'large-card-meta': 'large-card-meta',
  'large-card-price': 'large-card-price',
  'large-card-title': 'large-card-title',
  'limit-width': 'limit-width',
  'line-break': 'line-break',
  'link-button': 'link-button',
  'link-button-hover': 'link-button-hover',
  'link-button-hover-icon': 'link-button-hover-icon',
  'link-button-hover-url': 'link-button-hover-url',
  'link-button-icon': 'link-button-icon',
  'link-button-icon-container': 'link-button-icon-container',
  'link-button-title': 'link-button-title',
  'menu': 'menu',
  'menu-block': 'menu-block',
  'menu-bottom': 'menu-bottom',
  'menu-brand': 'menu-brand',
  'menu-brand-container': 'menu-brand-container',
  'menu-brand-image': 'menu-brand-image',
  'menu-button': 'menu-button',
  'menu-container': 'menu-container',
  'menu-sticky': 'menu-sticky',
  'menu-top': 'menu-top',
  'no-scrollpop': 'no-scrollpop',
  'node-bg': 'node-bg',
  'node-bg-node': 'node-bg-node',
  'parallax': 'parallax',
  'product-view': 'product-view',
  'product-view-attributes-container': 'product-view-attributes-container',
  'product-view-attributes-heading': 'product-view-attributes-heading',
  'product-view-content': 'product-view-content',
  'product-view-image': 'product-view-image',
  'product-view-image-container': 'product-view-image-container',
  'scrollpop': 'scrollpop',
  'search-bar': 'search-bar',
  'search-bar-input': 'search-bar-input',
  'text': 'text',
  'theme-bubble': 'theme-bubble'
} as const;

export type ClassName = (keyof typeof classNames);
export type PossibleClassName = ClassName | false | null | undefined;
export function useClasses(...args: PossibleClassName[]): string {
  const validClass = (arg: PossibleClassName) => !!(arg && arg in classNames);
  const validClasses = args.filter(validClass) as ClassName[];

  return validClasses.map(arg => classNames[arg]).join(' ');
}

